baseURL = 'https://quinns.dev/'

theme = "hugo-bearblog"

# Basic metadata configuration
title = "Quinns' Blog"
author = "Quinn Stevens"
copyright = "Copyright © 2024, Quinn Stevens"
languageCode = 'en-GB'
